name: test
on:
  push:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18'
      - name: test
        run: |
          sleep 240